### ISSUE TITLE
recommend disabling space highlighting in help files by default

### ISSUE THREAD

**Issue by markstos** [jpalardy/spacehi.vim#1]
Great little plugin. 

Help files light up like fireworks with SpaceHi, but since the reader is not editing the help files (usually), the highlighting is distracting there.

I recommend making ` au FileType help :NoSpaceHi` a default setting. 

I see it's already recommened in the source code, but I think making this the default would be a better experience for most people, most of the time.

**Comment by jpalardy** [comment]
hi @markstos 

sorry — I never got the notification for your message on this issue; now I stumbled on it a year later 😅 

I've got the exact same problem, which I ended up solving "manually":

```vim
augroup mostly_spacehi
  autocmd!
  autocmd Syntax * SpaceHi
  autocmd FileType help     NoSpaceHi
  autocmd FileType diff     NoSpaceHi
  autocmd FileType man      NoSpaceHi
  autocmd FileType scratchy NoSpaceHi
  autocmd FileType go       NoSpaceHi
  autocmd FileType make     NoSpaceHi
augroup END
```

I'm not sure setting those as defaults would _necessarily_ be a good idea. I can see how the reverse behavior (compared to the current behavior) could be as confusing…

How about adding a section to the README, do you think that would be helpful? If you send a PR, we can iterate on it.

Thanks

**Comment by markstos** [comment]
I don't see *not* making this a default behavior would a good idea. A note in the README could say something like:

*Since most people read Vim help files far more often than they write them, SpaceHi is disabled in this file format by default.*

**Comment by jpalardy** [comment]
If the plugin turns on the behavior, is there a way to turn it back off? (although unclear why… this will come up)

**Comment by markstos** [comment]
Perhaps a new variable could be used that is a list or array of blocked file types. The plugin would ship with some reasonable defaults and users can adjust the list as they like.

**Comment by jpalardy** [comment]
Hi there,

I'm closing this — I added a [new section](https://github.com/jpalardy/spacehi.vim#disabling-for-specific-filetypes) to the README.

I think this is 90% of the solution.
